#!/usr/bin/env bash
set -e

here="$(dirname "$0")"
here="$(cd "$here"; pwd)"

git submodule init
git submodule update

if [ ! \( -e "$HOME/.vimrc" \) ]; then
  ln -sfv "$here"/vimrc "${HOME}/.vimrc"
fi
